### PR TITLE
move cmd_args parameter to etcd.service dict

### PR DESCRIPTION
**Pull request by noelmcloughlin**
This PR fixes inconsistency - `cmd_args` parameter should exist under `service` dict not `docker` dict.  Also removed some unused params.

### CODE REVIEW

**Comment by aboe76** [comment]
@noelmcloughlin can you take a look why the checks are failing?

**Comment by noelmcloughlin** [comment]
Happy new year @aboe76  hope your doing good.  Okay, looks like two parameters I thought were superfluous are needed so I added back - PR was only to move `cmd_args` to correct dict.  I'll try to make time sometime to check if these two parameters are needed or not - future PR not now.  thanks
```
    auto-tls: True
    peer-auto-tls: True
```

**Comment by aboe76** [comment]
@noelmcloughlin thanks, you too happy new year, I'm doing fine.

**Comment by aboe76** [comment]
merged

**Pull request merged**
