### PR TITLE
Feature enhanced salt sdb driver

### PR DESCRIPTION
**Pull request by herisanu**
- allow directory creation through sdb
- allows dictionary of dictionary keys in sdb
- getting a directory, will return a dictionary, getting a leaf will return its value

Based on: https://github.com/saltstack-formulas/etcd-formula/pull/2

### CODE REVIEW

**Comment by herisanu** [comment]
**How to configure:**
Configure salt master and salt minion to add ```/var/cache/salt/minion/extmods``` to it salt loader path. When you sync the etcd-formula via ```salt-call saltutil.sync_all```, the loader will know of the new driver

```
    module_dirs:
      - /var/cache/salt/minion/extmods
```

You also must configure the etcd sdb in both salt minion and salt master. You can put this file in ```/etc/salt/master.d/myetcd.conf```, ```/etc/salt/minion.d/myetcd.conf``` respectively.

Example:
```
discovery:
    driver: mccs_etcd
    etcd.host: saltmaster.example.com
    etcd.port: 2379
```

**Comment by herisanu** [comment]
**Proof it works:**
Get a directory as Json:
```
[root@bastion ~]# salt-call sdb.get sdb://discovery/dynamic:mesos
local:
    ----------
    instances:
        ----------
        2:
            Hello world
        3:
            Hello world3
        4:
            ----------
            4:
                Hello world4
        5:
            Mumu
        6:
            ----------
            Test:
                Mama
[root@bastion ~]# 
```

Get a leaf value only:
```
[root@bastion ~]# salt-call sdb.get sdb://discovery/dynamic:mesos:instances:2
local:
    Hello world
[root@bastion ~]# 
```

Creating a directory with sdb.set:
You need to add : at the end of the path.
```
[root@bastion ~]# salt-call sdb.set sdb://discovery/dynamic:mesos:instances:7: ''
local:
    ----------
    7:
        ----------
[root@bastion ~]# 

```

Add a value in a multi dict structure:
```
[root@bastion ~]# salt-call sdb.set sdb://discovery/dynamic:mesos:instances:8:Test 'MyTest'
local:
    MyTest
[root@bastion ~]# 
```

Proof all sets worked:
```
[root@bastion ~]# salt-call sdb.get sdb://discovery/dynamic
local:
    ----------
    mesos:
        ----------
        instances:
            ----------
            2:
                Hello world
            3:
                Hello world3
            4:
                ----------
                4:
                    Hello world4
            5:
                Mumu
            6:
                ----------
                Test:
                    Mama
            7:
                ----------
            8:
                ----------
                Test:
                    MyTest
[root@bastion ~]# 
```

Proof runner works:
```
[root@saltmaster ~]# salt-run sdb.get sdb://discovery/dynamic:mesos
instances:
    ----------
    2:
        Hello world
    3:
        Hello world3
    4:
        ----------
        4:
            Hello world4
    5:
        Mumu
    6:
        ----------
        Test:
            Mama
    7:
        ----------
    8:
        ----------
        Test:
            MyTest
[root@saltmaster ~]# 
```

**Comment by noelmcloughlin** [comment]
Hi @herisanu the PR looks good but has gone stale.  Will you be revisiting? If you have no time the idea could be raised as issue before closing PR.

**Comment by noelmcloughlin** [comment]
Stale.

**Pull request closed without merging**
