### PR TITLE
Simplify etcd formula

### PR DESCRIPTION
**Pull request by herisanu**
Proposal to simplify the formula a bit so that we can adapt it for both systemd and upstart installation.

- updated script to install etcd
- created alterantives for etcd and etcdctl
- updated configuration procedure for systemd and upstart

Tested on Centos 7.2

The configuration for etcd will wary in time. I feel it's best to put the exact configuration in pillar and not compute the URLs. It makes it easier to read and update and you can use the grains logic in the pillar also.

### CODE REVIEW

**Comment by sc250024** [comment]
Was there anything wrong with this pull request? It should get merged.

**Comment by herisanu** [comment]
Removed the WIP at the front. I've been using this. The WIP was more to ask permission to redo the way this works. The proposed formula is not computing the URLs, but you have to give them in the pillar. I think this guarantees that you don't mess up the config.

**Comment by sc250024** [comment]
@herisanu I agree with your approach; let the pillar be more specific. I was also wanting to add support for doing discovery via DNS SRV records as well, which would require another environment variable. I was just hoping that this would get the official merge before I did that.

**Comment by herisanu** [comment]
@sc250024 what's the environment variable (too lazy to open up etcd page :|)
You can already use it. The environmental variables used are a merge between defaults.yaml and pillar.

```
{% for key,value in etcd.config.items() -%}
Environment={{ key }}={{ value }}
{% endfor %}
```

and
```
{# Update settings defaults from pillar data #}
{% set etcd = salt['pillar.get'](
    'etcd',
    default=default_settings.etcd,
    merge=True)
%}
```

The only foreseeable problem if you don't need a environment variable set in default.yaml
1

**Comment by noelmcloughlin** [comment]
Superceded by #7

**Comment by noelmcloughlin** [comment]
#7  was merged with these improvements. Thanks.

**Pull request closed without merging**
